/*
 * Auto-generated symbol table for ELF loader
 * DO NOT EDIT - Generated by tools/export_symbols.py
 */

#include <stddef.h>
#include "private/elf_symbol.h"

/* Extern declarations */
extern void shim_open(void);
extern void shim_read(void);
extern void shim_write(void);
extern void shim_close(void);
extern void shim_lseek(void);
extern void shim_ioctl(void);
extern void shim_fopen(void);
extern void fprintf(void);
extern void fclose(void);
extern void fread(void);
extern void fwrite(void);
extern void fflush(void);
extern void fseek(void);
extern void ftell(void);
extern void shim_stat(void);
extern void shim_fstat(void);
extern void shim_access(void);
extern void shim_unlink(void);
extern void shim_rename(void);
extern void shim_mkdir(void);
extern void shim_rmdir(void);
extern void shim_opendir(void);
extern void shim_readdir(void);
extern void shim_closedir(void);
extern void shim_getcwd(void);
extern void shim_chdir(void);
extern void vTaskDelay(void);
extern void vTaskDelete(void);
extern void xTaskGetCurrentTaskHandle(void);
extern void xQueueReceive(void);
extern void pvPortMalloc(void);
extern void vPortFree(void);
extern void esp_log_write(void);
extern void esp_log_timestamp(void);

/* Custom symbol table for ELF loader */
const struct esp_elfsym g_customer_elfsyms[] = {
    { "open", &shim_open },
    { "read", &shim_read },
    { "write", &shim_write },
    { "close", &shim_close },
    { "lseek", &shim_lseek },
    { "ioctl", &shim_ioctl },
    { "fopen", &shim_fopen },
    ESP_ELFSYM_EXPORT(fprintf),
    ESP_ELFSYM_EXPORT(fclose),
    ESP_ELFSYM_EXPORT(fread),
    ESP_ELFSYM_EXPORT(fwrite),
    ESP_ELFSYM_EXPORT(fflush),
    ESP_ELFSYM_EXPORT(fseek),
    ESP_ELFSYM_EXPORT(ftell),
    { "stat", &shim_stat },
    { "fstat", &shim_fstat },
    { "access", &shim_access },
    { "unlink", &shim_unlink },
    { "rename", &shim_rename },
    { "mkdir", &shim_mkdir },
    { "rmdir", &shim_rmdir },
    { "opendir", &shim_opendir },
    { "readdir", &shim_readdir },
    { "closedir", &shim_closedir },
    { "getcwd", &shim_getcwd },
    { "chdir", &shim_chdir },
    ESP_ELFSYM_EXPORT(vTaskDelay),
    ESP_ELFSYM_EXPORT(vTaskDelete),
    ESP_ELFSYM_EXPORT(xTaskGetCurrentTaskHandle),
    ESP_ELFSYM_EXPORT(xQueueReceive),
    ESP_ELFSYM_EXPORT(pvPortMalloc),
    ESP_ELFSYM_EXPORT(vPortFree),
    ESP_ELFSYM_EXPORT(esp_log_write),
    ESP_ELFSYM_EXPORT(esp_log_timestamp),
    ESP_ELFSYM_END
};
