/*
 * Auto-generated symbol table for ELF loader
 * DO NOT EDIT - Generated by tools/export_symbols.py
 */

#include <stddef.h>
#include "private/elf_symbol.h"

/* Extern declarations */
extern void shim_open(void);
extern void shim_read(void);
extern void shim_write(void);
extern void shim_close(void);
extern void shim_lseek(void);
extern void shim_ioctl(void);
extern void shim_fopen(void);
extern void shim_printf(void);
extern void shim_puts(void);
extern void fprintf(void);
extern void fclose(void);
extern void fread(void);
extern void fwrite(void);
extern void fflush(void);
extern void fseek(void);
extern void ftell(void);
extern void shim_stat(void);
extern void shim_fstat(void);
extern void shim_access(void);
extern void shim_unlink(void);
extern void shim_rename(void);
extern void shim_mkdir(void);
extern void shim_rmdir(void);
extern void shim_opendir(void);
extern void shim_readdir(void);
extern void shim_closedir(void);
extern void shim_getcwd(void);
extern void shim_chdir(void);
extern void shim_dup(void);
extern void shim_dup2(void);
extern void shim_dup3(void);
extern void shim_socket(void);
extern void shim_bind(void);
extern void shim_listen(void);
extern void shim_accept(void);
extern void shim_connect(void);
extern void shim_send(void);
extern void shim_sendto(void);
extern void shim_recv(void);
extern void shim_recvfrom(void);
extern void shim_shutdown(void);
extern void shim_setsockopt(void);
extern void shim_getsockopt(void);
extern void shim_select(void);
extern void shim_poll(void);
extern void shim_gethostbyname(void);
extern void shim_getaddrinfo(void);
extern void shim_freeaddrinfo(void);
extern void shim_getpid(void);
extern void shim_getppid(void);
extern void shim_fork(void);
extern void shim_execve(void);
extern void shim_waitpid(void);
extern void shim_wait(void);
extern void shim_exit(void);
extern void shim__exit(void);
extern void shim_abort(void);
extern void shim_signal(void);
extern void shim_raise(void);
extern void shim_kill(void);
extern void shim_clock_gettime(void);
extern void shim_gettimeofday(void);
extern void shim_nanosleep(void);
extern void shim_usleep(void);
extern void shim_sleep(void);
extern void shim_times(void);
extern void shim_alarm(void);
extern void shim_clock(void);
extern void shim_clock_getres(void);
extern void malloc(void);
extern void free(void);
extern void calloc(void);
extern void realloc(void);
extern void vfs_c2_pipe_register(void);
extern void c2_pipe_set_socket(void);
extern void c2_pipe_get_socket(void);
extern void c2_pipe_set_mirror(void);
extern void c2_pipe_is_active(void);
extern void vTaskDelay(void);
extern void vTaskDelete(void);
extern void xTaskGetCurrentTaskHandle(void);
extern void xQueueReceive(void);
extern void pvPortMalloc(void);
extern void vPortFree(void);
extern void gpio_set_level(void);
extern void gpio_get_level(void);
extern void gpio_set_direction(void);
extern void gpio_config(void);
extern void gpio_reset_pin(void);
extern void esp_log_write(void);
extern void esp_log_timestamp(void);
extern void strlen(void);
extern void strcpy(void);
extern void strncpy(void);
extern void strcat(void);
extern void strncat(void);
extern void strcmp(void);
extern void strncmp(void);
extern void strchr(void);
extern void strrchr(void);
extern void strstr(void);
extern void memset(void);
extern void memcpy(void);
extern void memmove(void);
extern void memcmp(void);
extern void strtod(void);
extern void strtol(void);
extern void strtoul(void);
extern void atoi(void);
extern void atol(void);
extern void snprintf(void);
extern void __floatsidf(void);
extern void __extendsfdf2(void);
extern void __adddf3(void);
extern void __divdf3(void);
extern void __truncdfsf2(void);
extern void __muldf3(void);
extern void __subdf3(void);
extern void __fixdfsi(void);
extern void __floatunsidf(void);
extern void __gedf2(void);
extern void __ledf2(void);
extern void __ltdf2(void);
extern void __gtdf2(void);
extern void __eqdf2(void);
extern void __nedf2(void);
extern void __divsf3(void);
extern void __addsf3(void);
extern void __subsf3(void);
extern void __mulsf3(void);
extern void sinf(void);
extern void cosf(void);
extern void tanf(void);
extern void asinf(void);
extern void acosf(void);
extern void atanf(void);
extern void atan2f(void);
extern void sqrtf(void);
extern void powf(void);
extern void expf(void);
extern void logf(void);
extern void log10f(void);
extern void fabsf(void);
extern void floorf(void);
extern void ceilf(void);
extern void fmodf(void);
extern void roundf(void);
extern void sin(void);
extern void cos(void);
extern void tan(void);
extern void atan(void);
extern void atan2(void);
extern void sqrt(void);
extern void pow(void);
extern void exp(void);
extern void log(void);
extern void fabs(void);
extern void floor(void);
extern void ceil(void);

/* Custom symbol table for ELF loader */
const struct esp_elfsym g_customer_elfsyms[] = {
    { "open", &shim_open },
    { "read", &shim_read },
    { "write", &shim_write },
    { "close", &shim_close },
    { "lseek", &shim_lseek },
    { "ioctl", &shim_ioctl },
    { "fopen", &shim_fopen },
    { "printf", &shim_printf },
    { "puts", &shim_puts },
    ESP_ELFSYM_EXPORT(fprintf),
    ESP_ELFSYM_EXPORT(fclose),
    ESP_ELFSYM_EXPORT(fread),
    ESP_ELFSYM_EXPORT(fwrite),
    ESP_ELFSYM_EXPORT(fflush),
    ESP_ELFSYM_EXPORT(fseek),
    ESP_ELFSYM_EXPORT(ftell),
    { "stat", &shim_stat },
    { "fstat", &shim_fstat },
    { "access", &shim_access },
    { "unlink", &shim_unlink },
    { "rename", &shim_rename },
    { "mkdir", &shim_mkdir },
    { "rmdir", &shim_rmdir },
    { "opendir", &shim_opendir },
    { "readdir", &shim_readdir },
    { "closedir", &shim_closedir },
    { "getcwd", &shim_getcwd },
    { "chdir", &shim_chdir },
    { "dup", &shim_dup },
    { "dup2", &shim_dup2 },
    { "dup3", &shim_dup3 },
    { "socket", &shim_socket },
    { "bind", &shim_bind },
    { "listen", &shim_listen },
    { "accept", &shim_accept },
    { "connect", &shim_connect },
    { "send", &shim_send },
    { "sendto", &shim_sendto },
    { "recv", &shim_recv },
    { "recvfrom", &shim_recvfrom },
    { "shutdown", &shim_shutdown },
    { "setsockopt", &shim_setsockopt },
    { "getsockopt", &shim_getsockopt },
    { "select", &shim_select },
    { "poll", &shim_poll },
    { "gethostbyname", &shim_gethostbyname },
    { "getaddrinfo", &shim_getaddrinfo },
    { "freeaddrinfo", &shim_freeaddrinfo },
    { "getpid", &shim_getpid },
    { "getppid", &shim_getppid },
    { "fork", &shim_fork },
    { "execve", &shim_execve },
    { "waitpid", &shim_waitpid },
    { "wait", &shim_wait },
    { "exit", &shim_exit },
    { "_exit", &shim__exit },
    { "abort", &shim_abort },
    { "signal", &shim_signal },
    { "raise", &shim_raise },
    { "kill", &shim_kill },
    { "clock_gettime", &shim_clock_gettime },
    { "gettimeofday", &shim_gettimeofday },
    { "nanosleep", &shim_nanosleep },
    { "usleep", &shim_usleep },
    { "sleep", &shim_sleep },
    { "times", &shim_times },
    { "alarm", &shim_alarm },
    { "clock", &shim_clock },
    { "clock_getres", &shim_clock_getres },
    ESP_ELFSYM_EXPORT(malloc),
    ESP_ELFSYM_EXPORT(free),
    ESP_ELFSYM_EXPORT(calloc),
    ESP_ELFSYM_EXPORT(realloc),
    ESP_ELFSYM_EXPORT(vfs_c2_pipe_register),
    ESP_ELFSYM_EXPORT(c2_pipe_set_socket),
    ESP_ELFSYM_EXPORT(c2_pipe_get_socket),
    ESP_ELFSYM_EXPORT(c2_pipe_set_mirror),
    ESP_ELFSYM_EXPORT(c2_pipe_is_active),
    ESP_ELFSYM_EXPORT(vTaskDelay),
    ESP_ELFSYM_EXPORT(vTaskDelete),
    ESP_ELFSYM_EXPORT(xTaskGetCurrentTaskHandle),
    ESP_ELFSYM_EXPORT(xQueueReceive),
    ESP_ELFSYM_EXPORT(pvPortMalloc),
    ESP_ELFSYM_EXPORT(vPortFree),
    ESP_ELFSYM_EXPORT(gpio_set_level),
    ESP_ELFSYM_EXPORT(gpio_get_level),
    ESP_ELFSYM_EXPORT(gpio_set_direction),
    ESP_ELFSYM_EXPORT(gpio_config),
    ESP_ELFSYM_EXPORT(gpio_reset_pin),
    ESP_ELFSYM_EXPORT(esp_log_write),
    ESP_ELFSYM_EXPORT(esp_log_timestamp),
    ESP_ELFSYM_EXPORT(strlen),
    ESP_ELFSYM_EXPORT(strcpy),
    ESP_ELFSYM_EXPORT(strncpy),
    ESP_ELFSYM_EXPORT(strcat),
    ESP_ELFSYM_EXPORT(strncat),
    ESP_ELFSYM_EXPORT(strcmp),
    ESP_ELFSYM_EXPORT(strncmp),
    ESP_ELFSYM_EXPORT(strchr),
    ESP_ELFSYM_EXPORT(strrchr),
    ESP_ELFSYM_EXPORT(strstr),
    ESP_ELFSYM_EXPORT(memset),
    ESP_ELFSYM_EXPORT(memcpy),
    ESP_ELFSYM_EXPORT(memmove),
    ESP_ELFSYM_EXPORT(memcmp),
    ESP_ELFSYM_EXPORT(strtod),
    ESP_ELFSYM_EXPORT(strtol),
    ESP_ELFSYM_EXPORT(strtoul),
    ESP_ELFSYM_EXPORT(atoi),
    ESP_ELFSYM_EXPORT(atol),
    ESP_ELFSYM_EXPORT(snprintf),
    ESP_ELFSYM_EXPORT(__floatsidf),
    ESP_ELFSYM_EXPORT(__extendsfdf2),
    ESP_ELFSYM_EXPORT(__adddf3),
    ESP_ELFSYM_EXPORT(__divdf3),
    ESP_ELFSYM_EXPORT(__truncdfsf2),
    ESP_ELFSYM_EXPORT(__muldf3),
    ESP_ELFSYM_EXPORT(__subdf3),
    ESP_ELFSYM_EXPORT(__fixdfsi),
    ESP_ELFSYM_EXPORT(__floatunsidf),
    ESP_ELFSYM_EXPORT(__gedf2),
    ESP_ELFSYM_EXPORT(__ledf2),
    ESP_ELFSYM_EXPORT(__ltdf2),
    ESP_ELFSYM_EXPORT(__gtdf2),
    ESP_ELFSYM_EXPORT(__eqdf2),
    ESP_ELFSYM_EXPORT(__nedf2),
    ESP_ELFSYM_EXPORT(__divsf3),
    ESP_ELFSYM_EXPORT(__addsf3),
    ESP_ELFSYM_EXPORT(__subsf3),
    ESP_ELFSYM_EXPORT(__mulsf3),
    ESP_ELFSYM_EXPORT(sinf),
    ESP_ELFSYM_EXPORT(cosf),
    ESP_ELFSYM_EXPORT(tanf),
    ESP_ELFSYM_EXPORT(asinf),
    ESP_ELFSYM_EXPORT(acosf),
    ESP_ELFSYM_EXPORT(atanf),
    ESP_ELFSYM_EXPORT(atan2f),
    ESP_ELFSYM_EXPORT(sqrtf),
    ESP_ELFSYM_EXPORT(powf),
    ESP_ELFSYM_EXPORT(expf),
    ESP_ELFSYM_EXPORT(logf),
    ESP_ELFSYM_EXPORT(log10f),
    ESP_ELFSYM_EXPORT(fabsf),
    ESP_ELFSYM_EXPORT(floorf),
    ESP_ELFSYM_EXPORT(ceilf),
    ESP_ELFSYM_EXPORT(fmodf),
    ESP_ELFSYM_EXPORT(roundf),
    ESP_ELFSYM_EXPORT(sin),
    ESP_ELFSYM_EXPORT(cos),
    ESP_ELFSYM_EXPORT(tan),
    ESP_ELFSYM_EXPORT(atan),
    ESP_ELFSYM_EXPORT(atan2),
    ESP_ELFSYM_EXPORT(sqrt),
    ESP_ELFSYM_EXPORT(pow),
    ESP_ELFSYM_EXPORT(exp),
    ESP_ELFSYM_EXPORT(log),
    ESP_ELFSYM_EXPORT(fabs),
    ESP_ELFSYM_EXPORT(floor),
    ESP_ELFSYM_EXPORT(ceil),
    ESP_ELFSYM_END
};
