/*
 * Auto-generated symbol table for ELF loader
 * DO NOT EDIT - Generated by tools/export_symbols.py
 */

#include <stddef.h>
#include "private/elf_symbol.h"

/* Extern declarations */
extern void shim_open(void);
extern void shim_read(void);
extern void shim_write(void);
extern void shim_close(void);
extern void shim_lseek(void);
extern void shim_ioctl(void);
extern void shim_fopen(void);
extern void shim_printf(void);
extern void shim_puts(void);
extern void fprintf(void);
extern void fclose(void);
extern void fread(void);
extern void fwrite(void);
extern void fflush(void);
extern void fseek(void);
extern void ftell(void);
extern void shim_stat(void);
extern void shim_fstat(void);
extern void shim_access(void);
extern void shim_unlink(void);
extern void shim_rename(void);
extern void shim_mkdir(void);
extern void shim_rmdir(void);
extern void shim_opendir(void);
extern void shim_readdir(void);
extern void shim_closedir(void);
extern void shim_getcwd(void);
extern void shim_chdir(void);
extern void shim_dup(void);
extern void shim_dup2(void);
extern void shim_dup3(void);
extern void shim_socket(void);
extern void shim_bind(void);
extern void shim_listen(void);
extern void shim_accept(void);
extern void shim_connect(void);
extern void shim_send(void);
extern void shim_sendto(void);
extern void shim_recv(void);
extern void shim_recvfrom(void);
extern void shim_shutdown(void);
extern void shim_setsockopt(void);
extern void shim_getsockopt(void);
extern void shim_select(void);
extern void shim_poll(void);
extern void shim_gethostbyname(void);
extern void shim_getaddrinfo(void);
extern void shim_freeaddrinfo(void);
extern void shim_getpid(void);
extern void shim_getppid(void);
extern void shim_fork(void);
extern void shim_execve(void);
extern void shim_waitpid(void);
extern void shim_wait(void);
extern void shim_exit(void);
extern void shim__exit(void);
extern void shim_abort(void);
extern void shim_signal(void);
extern void shim_raise(void);
extern void shim_kill(void);
extern void vfs_c2_pipe_register(void);
extern void c2_pipe_set_socket(void);
extern void c2_pipe_get_socket(void);
extern void c2_pipe_set_mirror(void);
extern void c2_pipe_is_active(void);
extern void vTaskDelay(void);
extern void vTaskDelete(void);
extern void xTaskGetCurrentTaskHandle(void);
extern void xQueueReceive(void);
extern void pvPortMalloc(void);
extern void vPortFree(void);
extern void gpio_set_level(void);
extern void gpio_get_level(void);
extern void gpio_set_direction(void);
extern void gpio_config(void);
extern void gpio_reset_pin(void);
extern void esp_log_write(void);
extern void esp_log_timestamp(void);

/* Custom symbol table for ELF loader */
const struct esp_elfsym g_customer_elfsyms[] = {
    { "open", &shim_open },
    { "read", &shim_read },
    { "write", &shim_write },
    { "close", &shim_close },
    { "lseek", &shim_lseek },
    { "ioctl", &shim_ioctl },
    { "fopen", &shim_fopen },
    { "printf", &shim_printf },
    { "puts", &shim_puts },
    ESP_ELFSYM_EXPORT(fprintf),
    ESP_ELFSYM_EXPORT(fclose),
    ESP_ELFSYM_EXPORT(fread),
    ESP_ELFSYM_EXPORT(fwrite),
    ESP_ELFSYM_EXPORT(fflush),
    ESP_ELFSYM_EXPORT(fseek),
    ESP_ELFSYM_EXPORT(ftell),
    { "stat", &shim_stat },
    { "fstat", &shim_fstat },
    { "access", &shim_access },
    { "unlink", &shim_unlink },
    { "rename", &shim_rename },
    { "mkdir", &shim_mkdir },
    { "rmdir", &shim_rmdir },
    { "opendir", &shim_opendir },
    { "readdir", &shim_readdir },
    { "closedir", &shim_closedir },
    { "getcwd", &shim_getcwd },
    { "chdir", &shim_chdir },
    { "dup", &shim_dup },
    { "dup2", &shim_dup2 },
    { "dup3", &shim_dup3 },
    { "socket", &shim_socket },
    { "bind", &shim_bind },
    { "listen", &shim_listen },
    { "accept", &shim_accept },
    { "connect", &shim_connect },
    { "send", &shim_send },
    { "sendto", &shim_sendto },
    { "recv", &shim_recv },
    { "recvfrom", &shim_recvfrom },
    { "shutdown", &shim_shutdown },
    { "setsockopt", &shim_setsockopt },
    { "getsockopt", &shim_getsockopt },
    { "select", &shim_select },
    { "poll", &shim_poll },
    { "gethostbyname", &shim_gethostbyname },
    { "getaddrinfo", &shim_getaddrinfo },
    { "freeaddrinfo", &shim_freeaddrinfo },
    { "getpid", &shim_getpid },
    { "getppid", &shim_getppid },
    { "fork", &shim_fork },
    { "execve", &shim_execve },
    { "waitpid", &shim_waitpid },
    { "wait", &shim_wait },
    { "exit", &shim_exit },
    { "_exit", &shim__exit },
    { "abort", &shim_abort },
    { "signal", &shim_signal },
    { "raise", &shim_raise },
    { "kill", &shim_kill },
    ESP_ELFSYM_EXPORT(vfs_c2_pipe_register),
    ESP_ELFSYM_EXPORT(c2_pipe_set_socket),
    ESP_ELFSYM_EXPORT(c2_pipe_get_socket),
    ESP_ELFSYM_EXPORT(c2_pipe_set_mirror),
    ESP_ELFSYM_EXPORT(c2_pipe_is_active),
    ESP_ELFSYM_EXPORT(vTaskDelay),
    ESP_ELFSYM_EXPORT(vTaskDelete),
    ESP_ELFSYM_EXPORT(xTaskGetCurrentTaskHandle),
    ESP_ELFSYM_EXPORT(xQueueReceive),
    ESP_ELFSYM_EXPORT(pvPortMalloc),
    ESP_ELFSYM_EXPORT(vPortFree),
    ESP_ELFSYM_EXPORT(gpio_set_level),
    ESP_ELFSYM_EXPORT(gpio_get_level),
    ESP_ELFSYM_EXPORT(gpio_set_direction),
    ESP_ELFSYM_EXPORT(gpio_config),
    ESP_ELFSYM_EXPORT(gpio_reset_pin),
    ESP_ELFSYM_EXPORT(esp_log_write),
    ESP_ELFSYM_EXPORT(esp_log_timestamp),
    ESP_ELFSYM_END
};
